// Generated by CoffeeScript 1.6.1
var chooser, file, files, filetype, _i, _len;

files = $('#files .file');

for (_i = 0, _len = files.length; _i < _len; _i++) {
  file = files[_i];
  file = $(file);
  filetype = 'JSON';
  chooser = $("<div class=\"select-menu js-menu-container js-select-menu js-period-container\"\n	style=\"line-height: 33px; float: right; margin-right: 8px;\">\n	<span class=\"minibutton select-menu-button js-menu-target\">\n		<i>Tab size:</i>\n		<span class=\"js-select-button\"> 4</span>\n	</span>\n	<div class=\"select-menu-modal-holder js-menu-content js-navigation-container\"\n		style=\"line-height: 1.4\">\n		<div class=\"select-menu-modal\">\n			<div class=\"select-menu-header\">\n				<span class=\"select-menu-title\">Tab size (" + filetype + ")</span>\n				<span class=\"mini-icon mini-icon-remove-close js-menu-close\"></span>\n			</div>\n			<div class=\"select-menu-list\">\n				<div class=\"select-menu-item js-navigation-item js-navigation-target\">\n					<input id=\"tabsize_2\" name=\"tabsize\" type=\"radio\" value=\"2\" />\n					<span class=\"select-menu-item-icon mini-icon mini-icon-confirm\"></span>\n					<div class=\"select-menu-item-text js-select-button-text\">2</div>\n				</div>\n				<div class=\"select-menu-item js-navigation-item js-navigation-target selected\">\n					<input id=\"tabsize_4\" name=\"tabsize\" type=\"radio\" value=\"4\" />\n					<span class=\"select-menu-item-icon mini-icon mini-icon-confirm\"></span>\n					<div class=\"select-menu-item-text js-select-button-text\">4</div>\n				</div>\n				<div class=\"select-menu-item js-navigation-item js-navigation-target\">\n					<input id=\"tabsize_8\" name=\"tabsize\" type=\"radio\" value=\"8\" />\n					<span class=\"select-menu-item-icon mini-icon mini-icon-confirm\"></span>\n					<div class=\"select-menu-item-text js-select-button-text\">8</div>\n				</div>\n			</div>\n		</div>\n	</div>\n</div>");
  chooser.find('.select-menu-item').on('mouseenter', function(event) {
    return $(this).addClass('navigation-focus');
  }).on('mouseleave', function(event) {
    return $(this).removeClass('navigation-focus');
  });
  chooser.appendTo(file.find('.meta'));
}
