// Generated by CoffeeScript 1.6.1
var filetype, load, menu, nameFromType;

nameFromType = function(type) {
  var names;
  names = {
    c: 'C/C++/C#',
    css: 'CSS',
    coffeescript: 'CoffeeScript',
    javascript: 'JavaScript',
    json: 'JSON',
    less: 'LESS',
    makefile: 'Makefile',
    'objective-c': 'Objective-C',
    ruby: 'Ruby',
    text: 'Plain Text'
  };
  return names[type] || type;
};

filetype = function(file) {
  var match, str;
  str = file.children('div').get(1).className;
  match = str.match(/type-([_a-zA-Z0-9-]+)/);
  if (match.length > 1) {
    return match[1];
  } else {
    return false;
  }
};

menu = function(type) {
  var indent;
  return $('<div>').addClass('select-menu').addClass('js-menu-container').addClass('js-select-menu').addClass('js-period-container').css('line-height', '33px').css('float', 'right').css('margin-right', '8px').append($('<span>').addClass('minibutton').addClass('select-menu-button').addClass('js-menu-target').append($('<i>').text('indent size:')).append($('<span>').addClass('js-select-button').text(' 4'))).append($('<div>').addClass('select-menu-modal-holder').addClass('js-menu-content').addClass('js-navigation-container').css('line-height', '1.4').append($('<div>').addClass('select-menu-modal').append($('<div>').addClass('select-menu-header').append($('<span>').addClass('select-menu-title').text("Select Indentation Size (" + (nameFromType(type)) + ")")).append($('<span>').addClass('mini-icon').addClass('mini-icon-remove-close').addClass('js-menu-close'))).append($('<div>').addClass('select-menu-list').append((function() {
    var _i, _len, _ref, _results;
    _ref = [2, 4, 8];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      indent = _ref[_i];
      _results.push($('<div>').addClass('select-menu-item').addClass('js-navigation-item').addClass('js-navigation-target').append($('<input>').attr({
        id: "tabsize_" + indent,
        name: 'tabsize',
        type: 'radio'
      }).val(indent)).append($('<span>').addClass('select-menu-item-icon').addClass('mini-icon').addClass('mini-icon-confirm')).append($('<div>').addClass('select-menu-item-text').addClass('js-select-button-text').text(indent)));
    }
    return _results;
  })()))));
};

load = function(files) {
  var chooser, file, type, _i, _len, _ref, _results;
  _ref = (function() {
    var _j, _len, _results1;
    _results1 = [];
    for (_j = 0, _len = files.length; _j < _len; _j++) {
      file = files[_j];
      _results1.push($(file));
    }
    return _results1;
  })();
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    type = filetype(file);
    if (!type) {
      continue;
    }
    chooser = menu(type);
    chooser.find('.select-menu-item').on('mouseenter', function(event) {
      return $(this).addClass('navigation-focus');
    }).on('mouseleave', function(event) {
      return $(this).removeClass('navigation-focus');
    });
    _results.push(chooser.appendTo(file.find('.meta')));
  }
  return _results;
};

load($('#files .file'));
